from django.contrib import admin

from .models import (
    Banner,
    ContactInfo,
    About,
    ServiceItem,
    Service,
    Whychoose,
    Projectcategory,
    ProjectItem,
    Projects,
    Team,
    TestItem,
    Testimonial,
    Blogscategory,
    Blogstag,
    Blogsparagraph,
    Blogsitem,
    BlogReview,
    ReplayBlogReview,
    Newslatter,
    Contact,
)

admin.site.register([
    Banner,
    ContactInfo,
    About,
    ServiceItem,
    Service,
    Whychoose,
    Projectcategory,
    ProjectItem,
    Projects,
    Team,
    TestItem,
    Testimonial,
    Blogscategory,
    Blogstag,
    Blogsparagraph,
    Blogsitem,
    BlogReview,
    ReplayBlogReview,
    Newslatter,
    Contact,
])