export { default as Banner } from "./Banner/Banner";
export { default as Contactinfo } from "./Contactinfo/Contactinfo";
export { default as About } from "./About/About";
export { default as Service } from "./Service/Service";
export { default as Whychoose } from "./Whychoose/Whychoose";
export { default as Projects } from "./Projects/Projects";
export { default as Team } from "./Team/Team";
export { default as Testimonial } from "./Testimonial/Testimonial";
export { default as Blog } from "./Blog/Blog";
