# Generated by Django 4.2.7 on 2024-01-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgae', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('experiance', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='banner/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Banners',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=55, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('facebook_link', models.CharField(blank=True, null=True)),
                ('twitter_link', models.CharField(blank=True, null=True)),
                ('linkedin_link', models.CharField(blank=True, null=True)),
                ('instagram_link', models.CharField(blank=True, null=True)),
                ('youtube_link', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='Newslatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Newslatter',
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgae', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('live', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Complete', 'Complete'), ('Upcomming', 'Upcomming')], max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project item',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service item',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Teammember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgae', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True)),
            ],
            options={
                'verbose_name_plural': 'Team member',
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgae', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonial Item',
            },
        ),
        migrations.CreateModel(
            name='Whychoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgae', models.ImageField(blank=True, null=True, upload_to='whychoose/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('cleaners', models.PositiveBigIntegerField()),
                ('clients', models.PositiveBigIntegerField()),
                ('projects', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Whychoose',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('imgae', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('item', models.ManyToManyField(blank=True, to='core.testitem')),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('item', models.ManyToManyField(blank=True, to='core.serviceitem')),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('item', models.ManyToManyField(blank=True, to='core.projectitem')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
